route:
    group_by: [...]
    group_interval: 5m
    group_wait: 10s
    receiver: 'slack'
    repeat_interval: 4h

receivers:     
  - name: 'slack'
    slack_configs:
    - channel: '#CHANNEL'
      # api_url: 'https://hooks.slack.com/services/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j'
      api_url: '<YOUR URL>'
      send_resolved: true
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
      title_link: 'https://<ALERTMANAGER-URL>/#/alerts'
      text: >-
       {{ range .Alerts }}
           *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
         *Description:* {{ .Annotations.description }}
         *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
         *Details:*
         {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
         {{ end }}
       {{ end }}